language: haskell
ghc: 7.8
install:
 - cabal install --dependencies-only
 - cabal configure
 - cabal build
 - cabal install --enable-tests --dependencies-only
 - cabal configure --enable-tests
script: make